import { Poppins } from 'next/font/google'
import '@/styles/globals.css'
import { Providers } from './providers'
import { ClerkProvider } from '@clerk/nextjs'

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'], subsets: ['latin']
})

export const metadata = {
  title: 'Siperpus SDN Wirogunan',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}> <ClerkProvider> <Providers>{children}</Providers></ClerkProvider></body>
    </html>


  )
}
